### ISSUE TITLE
Tests failen aufgrund von fehlender Datei

### ISSUE THREAD

**Issue by gilbus** [jbetzend/steinerTrees#1]
Also wirklich Martin, das geht doch wirklich nicht ;P

Tests in error: 
  pruneTest(util.AdjacencyListTest): 6
  testGetEdgeIndex(util.AdjacencyListTest): 11
  parseTest(util.ParserTest): /homes/msauer/Documents/input_100.csv (No such file or directory)

**Comment by msauerTechfak** [comment]
https://www.youtube.com/watch?v=KIBw10VUcNQ
